# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.version.version)

1.19.5


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
b=np.ones(20)
c=np.size(b)
print(c)

20


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
c=5+np.arange(20)
a=np.info(np.add(b,c))
print(a)

None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
c=np.zeros(10)
c[4]=1
print(c)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
d=10+np.arange(40)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
e=np.arange(10)
print(e[::-1])

[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
f=np.arange(9).reshape(3,3)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
d=[1,2,0,0,4,0]
e=np.nonzero(d)
print(e)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
e=np.eye(3,3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
f=np.random.random((3,3,3))
print(f)

[[[0.66694389 0.26214109 0.35878433]
  [0.1511084  0.50401023 0.41517115]
  [0.57471408 0.88346477 0.3351851 ]]

 [[0.96358592 0.26558469 0.39989534]
  [0.58728308 0.30371215 0.50692184]
  [0.06833462 0.4942845  0.48149784]]

 [[0.61231915 0.31692061 0.11173327]
  [0.2622129  0.50208703 0.13919524]
  [0.24395534 0.31090896 0.07385928]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
f=np.random.random(10)
g=f.min()
h=f.max()
print(g,h)

0.04709127384171552 0.8084534263425159


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
g=np.random.random(30)
h=np.mean(g)
print(h)

0.5723236372103059


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a=np.ones((7,7))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a=np.ones((7,7))
b=np.pad(a,pad_width=1,constant_values=0)
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
a=0*np.nan
print(a)
b=(np.nan == np.nan)
print(b)
c=np.inf>np.nan
print(c)
d=np.nan-np.nan
print(d)
e= (0.3 == (3*0.1))
print(e)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
a=np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
a=np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
a=np.unravel_index(100,(6,7,8))
print(a)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
b=np.array([[0,1],[1,0]])
print(b)
c=np.tile(b,(4,4))
print(c)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
s=np.random.random((5,5))
d=s.min()
e=s.max()
f=d/e
print(f)

0.022147778095630337


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
a=np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a=np.arange(15).reshape((5,3))
print(a)
c=np.arange(6).reshape((3,2))
print(c)
e=np.dot(a,c)
print(e)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x=np.arange(10)
x[(x >=3)&(x <=8)]=0
print(x)

[0 1 2 0 0 0 0 0 0 9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
a=np.sum(range(5),-1)
print(a)

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
a=2
b=a**a
print(b)
c=2<<a>>2
print(c)
d=a<-a
print(d)
e=1j*a
print(e)
f=a/1/1
print(f)
g=a<a>a
print(g)

4
2
False
2j
2.0
False


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
a=np.array(0)/np.array(0)
print(a)
b=np.array(0)//np.array(0)
print(b)
c=np.array([np.nan]).astype(int).astype(float)
print(c)

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
b=np.random.uniform(-10,10,10)
print(b)
d=np.abs(b)
print(d)
e=np.ceil(b)
print(e)
c=np.copysign(np.ceil(np.abs(b)),b)
print(c)

[ 3.31604538  8.78249198 -9.32986883  1.9287281  -7.09354101 -1.82282891
 -8.56958308  5.90985414  3.96846009  4.8844244 ]
[3.31604538 8.78249198 9.32986883 1.9287281  7.09354101 1.82282891
 8.56958308 5.90985414 3.96846009 4.8844244 ]
[ 4.  9. -9.  2. -7. -1. -8.  6.  4.  5.]
[  4.   9. -10.   2.  -8.  -2.  -9.   6.   4.   5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a=np.arange(15)
b=10+np.arange(15)
c=np.intersect1d(a,b)
print(c)

[10 11 12 13 14]


#### 31.How to ignore all numpy warnings (not recommended)? (★☆☆)  
(**hint**: np.seterr, np.errstate)

In [ ]:
a=np.sterr(all='ignore')
b=np.zeros(1)/100
print(b)

[0.]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
a=np.sqrt(-1)
b=np.emath.sqrt(-1)
if a==b:
  print('True')
else:
  print('False')

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
a=np.datetime64('today','D')
print(a)
b=a + np.timedelta64(1,'D')
print(b)
c=a-np.timedelta64(1,'D')
print(c)

2022-02-16
2022-02-17
2022-02-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
a=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a=2
b=4
c=np.add(a,b)
d=np.negative(a)
e=np.divide(d,2)
f=np.multiply(c,e)
print(f)

-6.0


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[8. 2. 4. 3. 7. 2. 1. 2. 4. 6.]
[8. 2. 4. 3. 7. 2. 1. 2. 4. 6.]
[8. 2. 4. 3. 7. 2. 1. 2. 4. 6.]
[8 2 4 3 7 2 1 2 4 6]
[8. 2. 4. 3. 7. 2. 1. 2. 4. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a=np.zeros((5,5))
a+=np.arange(5)
print(a)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def gen():
  for i in range(10):
    yield i
a=np.fromiter(gen(),dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
Z = np.linspace(0,1,10,endpoint=False)
print(Z)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
a=1+np.random.random(10)
b=np.sort(a)
print(b)

[1.1133363  1.95974423 1.34329022 1.11716283 1.57223523 1.17234666
 1.68096411 1.33399718 1.00981756 1.77803169]
[1.00981756 1.1133363  1.11716283 1.17234666 1.33399718 1.34329022
 1.57223523 1.68096411 1.77803169 1.95974423]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
a=np.arange(10)
b=np.add.reduce(a)
print(b)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
a=np.random.random(10)
b=np.random.random(10)
c=np.allclose(a,b)
print(c)
d=np.array_equal(b,a)
print(d)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
a=np.arange(10)
a.flags.writeable=False
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a=np.random.random((10,2))
print(a)
x=a[:,0]
y=a[:,1]
b=np.sqrt((x**2)+(y**2))
c=np.arctan2(x,y)
print(b)
print(c)

[[0.76029464 0.09849651]
 [0.41498321 0.63650508]
 [0.53770156 0.80552994]
 [0.32744924 0.82378132]
 [0.67996634 0.57394903]
 [0.26946445 0.03324996]
 [0.75311717 0.30365023]
 [0.43231791 0.07608855]
 [0.53250182 0.64233565]
 [0.86560349 0.00612148]]
[0.76664823 0.75983537 0.96850475 0.88647542 0.88981555 0.2715081
 0.81202767 0.43896268 0.834358   0.86562514]
[1.44196343 0.57775996 0.58858817 0.37834533 0.86974657 1.44802416
 1.18754193 1.39657921 0.69218058 1.56372452]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
a=np.random.random(10)
a[a.argmax()]=0
print(a)

[0.01533832 0.         0.78837806 0.63282163 0.60345247 0.27674577
 0.44283464 0.17541028 0.28698105 0.67935551]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
a=np.zeros((5,5),[('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
a=np.arange(10)
b=10+np.arange(10)
c=1/(np.subtract.outer(a, b))
d=np.linalg.det(c)
print(d)

-2.164202861343284e-53


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for i in [np.int16,np.int32,np.int64]:
  print(np.iinfo(i).max)
  print(np.iinfo(i).min)
  #print(np.iinfo(i).eps)
for i in [np.float16,np.float32,np.float64,np.float128]:
  print(np.finfo(i).max)
  print(np.finfo(i).min)
  print(np.finfo(i).eps)

32767
-32768
2147483647
-2147483648
9223372036854775807
-9223372036854775808
65500.0
-65500.0
0.000977
3.4028235e+38
-3.4028235e+38
1.1920929e-07
1.7976931348623157e+308
-1.7976931348623157e+308
2.220446049250313e-16
1.189731495357231765e+4932
-1.189731495357231765e+4932
1.084202172485504434e-19


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=None)
a=np.zeros((19,19))
print(a)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
a=np.arange(100)
b=np.random.uniform(0,100)
print(b)
c=np.abs(a-b).argmin()
print(a[c])

46.62473957657388
47


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
a= np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]), ('color',[ ('r', float, 1),('g', float, 1),('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((10,2))
print(Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.89561376 0.48993401]
 [0.47290121 0.59946718]
 [0.99854956 0.78163612]
 [0.20590043 0.79521915]
 [0.97529444 0.15218821]
 [0.0537086  0.89725826]
 [0.84575527 0.03935107]
 [0.52211975 0.11266021]
 [0.72673013 0.08967591]
 [0.41333945 0.04207762]]
[[0.         0.43667311 0.30933138 0.75425691 0.34701764 0.93526324
  0.45333306 0.53087974 0.43442862 0.65815185]
 [0.43667311 0.         0.55631979 0.33107137 0.67264956 0.51420032
  0.67286716 0.48928876 0.56948771 0.56056287]
 [0.30933138 0.55631979 0.         0.7927655  0.62987735 0.95188913
  0.75784774 0.8212881  0.74343442 0.94308942]
 [0.75425691 0.33107137 0.7927655  0.         1.00272425 0.183233
  0.99032862 0.75225086 0.87695771 0.78118698]
 [0.34701764 0.67264956 0.62987735 1.00272425 0.         1.18509486
  0.17179237 0.45489533 0.25630451 0.57264103]
 [0.93526324 0.51420032 0.95188913 0.183233   1.18509486 0.
  1.16762266 0.91378504 1.05125982 0.92772208]
 [0.45333306 0.67286716 0.75784774 0.99032862 0.17179237 1.16762266
 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
A=np.arange(20,dtype=np.float32)
A=A.astype(np.int32)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
a= StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
b= np.genfromtxt(a, delimiter=",", dtype=np.int)
print(b)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a= np.arange(6).reshape(3,2)
for index, value in np.ndenumerate(Z):
    print(index, value)
a.shape

(0, 0) 0.8956137558272605
(0, 1) 0.48993401352035293
(1, 0) 0.47290121331333645
(1, 1) 0.5994671833258813
(2, 0) 0.9985495629298095
(2, 1) 0.7816361223801077
(3, 0) 0.20590043110247724
(3, 1) 0.795219149271694
(4, 0) 0.9752944375482474
(4, 1) 0.1521882074119293
(5, 0) 0.053708600311252686
(5, 1) 0.8972582571040708
(6, 0) 0.845755268834244
(6, 1) 0.039351065524219186
(7, 0) 0.5221197473810333
(7, 1) 0.11266021268970172
(8, 0) 0.7267301265910014
(8, 1) 0.08967591272743614
(9, 0) 0.41333944566579084
(9, 1) 0.04207762159511064


(3, 2)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
a,b=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
c=np.sqrt(a**2+b**2)
sigma, mu = 1.0, 0.0
d=np.exp(-( (c-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(d)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
a= 3
b = np.zeros((10,10))
np.put(b,[3,45,22],1)
print(b)

[20  0 16]
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
a=10+np.random.random((5,5))
print(a)
b=a-np.mean(a,axis=1)
print(b)


[[10.68358411 10.6568464  10.56106084 10.83913258 10.82878492]
 [10.27307461 10.71699332 10.34400362 10.98548646 10.11126622]
 [10.83874765 10.04268684 10.53038015 10.0417537  10.75326638]
 [10.60464474 10.08646739 10.69641019 10.37635337 10.58222793]
 [10.18019623 10.18336092 10.0036866  10.45092961 10.26679453]]
[[-0.03029766  0.17068155  0.1196939   0.36991186  0.61179134]
 [-0.44080716  0.23082848 -0.09736333  0.51626574 -0.10572735]
 [ 0.12486588 -0.443478    0.08901321 -0.42746702  0.53627281]
 [-0.10923703 -0.39969746  0.25504325 -0.09286736  0.36523436]
 [-0.53368554 -0.30280393 -0.43768035 -0.01829112  0.04980095]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
a=np.random.random(25).reshape(5,5)
print(a)
b=a[a[:,1].argsort()]
print(b)
a[:,1]

[[0.87140816 0.466538   0.33535396 0.85941611 0.4856001 ]
 [0.84200144 0.3139486  0.80489977 0.90799062 0.06809697]
 [0.06410107 0.00977807 0.60973696 0.22870203 0.13982512]
 [0.3148281  0.05295681 0.33219939 0.04825141 0.56791732]
 [0.33541869 0.81965772 0.56087469 0.2394529  0.23566932]]
[[0.06410107 0.00977807 0.60973696 0.22870203 0.13982512]
 [0.3148281  0.05295681 0.33219939 0.04825141 0.56791732]
 [0.84200144 0.3139486  0.80489977 0.90799062 0.06809697]
 [0.87140816 0.466538   0.33535396 0.85941611 0.4856001 ]
 [0.33541869 0.81965772 0.56087469 0.2394529  0.23566932]]


array([0.466538  , 0.3139486 , 0.00977807, 0.05295681, 0.81965772])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
a=np.random.random(25).reshape(5,5)
b=np.isnan(a)
print(b)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
a=3
b=np.arange(15).reshape(3,5)
c=b.flat[np.abs(b-a).argmin()]
print(c)

3


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a=np.random.random((1,3))
b=5+np.random.random((3,1))
print(a)
print(b)
c=np.nditer([a,b])
print(c)
for x,y in c:
  print([x+y])

[[0.89177511 0.31971541 0.22222501]]
[[5.76242852]
 [5.53117206]
 [5.00430791]]
[6.654203631247219]
[6.082143933602678]
[5.984653534595923]
[6.422947166225734]
[5.850887468581194]
[5.753397069574438]
[5.896083022910974]
[5.324023325266434]
[5.2265329262596785]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
a=np.random.randint(0,5,20)
print(a)
b=np.ones(5)
b+=np.bincount(a,minlength=0)
print(b)
np.add.at(b,a,1)
print(b)

[3 3 3 0 0 2 4 1 2 2 1 1 0 0 0 1 4 3 0 3]
[7. 5. 4. 6. 3.]
[13.  9.  7. 11.  5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
a=[1,2,3,4,5,6]
b=[1,2,9,0,4,1]
c=np.bincount(b,a)
print(c)

[4. 7. 2. 0. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w=8
h=8
a=np.random.randint(0,3,(w,h,4)).astype(np.int16)
b=a[:,0]*(256*256)+a[:,1]*(256*256)+a[:,2]*(256*256)+a[:,3]*(256*256)
c=len(np.unique(b))
print(c)

[[262144 196608 196608 393216]
 [131072 327680 458752 196608]
 [ 65536 196608 327680 131072]
 [458752 196608 262144 327680]
 [196608 327680 327680 393216]
 [262144 393216 327680 327680]
 [327680 131072 262144 458752]
 [524288 262144 196608 262144]]
8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
a=np.random.randint(0,30,(4,4,4,4))
b=a.sum(axis=(-2,-1))
print(b)

[[239 218 158 261]
 [225 240 250 272]
 [197 256 223 236]
 [265 208 193 249]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
d=np.random.uniform(0,10,10)
s=np.random.randint(0,10,10)
print(d)
print(s)
a=np.bincount(s,weights=d)
print(a)
b=np.bincount(s)
print(b)
c=a/b
print(c)

[0.03119459 3.39394397 2.072283   4.91767366 5.43875044 5.60524721
 8.79085291 1.83506598 5.29762235 7.96611637]
[6 6 2 0 1 5 7 4 7 7]
[ 4.91767366  5.43875044  2.072283    0.          1.83506598  5.60524721
  3.42513856 22.05459163]
[1 1 1 0 1 1 2 3]
[4.91767366 5.43875044 2.072283          nan 1.83506598 5.60524721
 1.71256928 7.35153054]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a=np.random.uniform(0,10,(4,4))
b=np.random.randint(0,10,(4,4))
c=np.diag(np.dot(a,b))
print(c)

[107.03115754 149.8097768  157.9053289  155.2616893 ]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
a=[1,2,3,4,5]
no_of_zeros=3
b=np.zeros(len(a)+((len(a)-1)*no_of_zeros))
b[::(no_of_zeros+1)]=a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a=np.random.randint(1,25,(5,5,3))
b=np.random.uniform(5,20,(5,5))
c=a*b[:,:,None]
print(c)

[[[101.66514711 152.49772067  29.04718489]
  [113.51913569 264.87798329 189.19855949]
  [ 82.60899757 396.52318833 214.78339368]
  [ 22.72470522 204.52234698 159.07293654]
  [336.31899555 269.05519644 168.15949778]]

 [[246.07850041 233.12700039 116.5635002 ]
  [362.48151409  90.62037852 166.13736062]
  [285.63586251 403.25062943 352.84430075]
  [ 82.75472147 189.15364909  23.64420614]
  [166.91516782 185.46129758  18.54612976]]

 [[ 34.69982125  46.26642833 161.93249917]
  [181.00349422  90.50174711 211.17074325]
  [ 74.83311657  18.70827914 355.45730369]
  [235.83931495  86.88816866 260.66450599]
  [167.541742   243.69707927 198.00387691]]

 [[193.52544196 112.88984115 370.92376376]
  [403.45967847 403.45967847 368.37622817]
  [ 64.67413119 194.02239356  21.55804373]
  [ 61.23065658  36.73839395 257.16875765]
  [317.5527589  331.98697521 245.38167733]]

 [[ 47.36179487  94.72358974  65.12246795]
  [339.69713138 212.31070711 268.92689568]
  [ 55.2447     349.88309999 128.9043    ]
  [

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
a=np.random.uniform(1,20,(5,5))
print(a)
a[[0,2]]=a[[2,0]]
print(a)

[[15.71576311 10.29235888 10.26166618 19.9359999   8.02488768]
 [17.11512694  9.92949896  7.7058341   8.48287537  2.44792466]
 [ 8.5891595   8.8940308  16.35501704  6.7283655  19.64217426]
 [17.95770272 19.17502713 18.43839481 16.87318305 16.48129349]
 [ 6.24532112 13.56761735 16.04663398  5.44654186 14.92973485]]
[[ 8.5891595   8.8940308  16.35501704  6.7283655  19.64217426]
 [17.11512694  9.92949896  7.7058341   8.48287537  2.44792466]
 [15.71576311 10.29235888 10.26166618 19.9359999   8.02488768]
 [17.95770272 19.17502713 18.43839481 16.87318305 16.48129349]
 [ 6.24532112 13.56761735 16.04663398  5.44654186 14.92973485]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
a=np.random.randint(0,100,(10,3))
b=np.roll(a.repeat(2,axis=1),-1,axis=1)
c=b.reshape(len(b)*3,2)
c=np.sort(c,axis=1)
d=c.view( dtype=[('p0',c.dtype),('p1',c.dtype)] )
d=np.unique(d)
print(d)

[( 1, 53) ( 1, 58) ( 4, 27) ( 4, 99) ( 6, 20) ( 6, 63) ( 9, 37) ( 9, 84)
 (11, 40) (11, 76) (12, 13) (12, 64) (13, 64) (14, 33) (14, 47) (16, 69)
 (16, 78) (20, 63) (22, 85) (27, 99) (28, 30) (28, 62) (30, 62) (33, 47)
 (37, 84) (40, 76) (53, 58) (69, 78) (85, 85)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
c=np.bincount([1,1,2,2,3,3,4])
b=np.repeat(np.arange(len(c)),c)
print(b)

[1 1 2 2 3 3 4]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
a=np.arange(20)
print(a)
b=np.cumsum(a)
print(b)
b[3:]=b[3:]-b[:-3]
b=b[3-1:]/3
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
a=(np.arange(10))
print(a)
from numpy.lib import stride_tricks
print(a.size)
print(a.itemsize)
b=(a.size-3+1,3)
c=(a.itemsize,a.itemsize)
d=stride_tricks.as_strided(a,b,c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
10
8
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
a=np.random.randint(0,2,50)
np.logical_not(a,out=a)
print(a)
b=np.random.uniform(-0.3,0.3,60)
print(b)
np.negative(b,out=b)
print(b)

[1 1 1 0 1 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 0 1 1 1 0
 1 1 1 0 0 1 0 0 0 0 0 1 1]
[ 0.29098446 -0.07522198 -0.03150367 -0.2888846  -0.04846247  0.12900597
  0.12272688  0.06885863  0.18884808  0.18232872  0.12363218 -0.25340779
 -0.23807168  0.26032069  0.20723602 -0.03239994 -0.14451549 -0.28493327
 -0.26025417 -0.29920898  0.04225548  0.11937629  0.14671881  0.1187484
  0.20266301 -0.23964958  0.21448218  0.22132187 -0.02878282  0.14978488
 -0.15565306 -0.24825836 -0.29726296 -0.27570794 -0.05249605 -0.10058551
  0.08087358 -0.21803607  0.21619333 -0.22509184  0.29659215  0.13598527
 -0.02256294  0.00891552 -0.20800913  0.25603789  0.07728834 -0.10637051
 -0.17959885  0.17863184 -0.15071707  0.29821582  0.12320086 -0.0033191
 -0.11436081 -0.29573917 -0.2291805   0.22104382  0.17592729 -0.08765921]
[-0.29098446  0.07522198  0.03150367  0.2888846   0.04846247 -0.12900597
 -0.12272688 -0.06885863 -0.18884808 -0.18232872 -0.12363218  0.25340779
  0.23807168 -0.260320

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
a=np.random.randint(-20,20,(10,2))
print(a)
b=np.random.randint(-10,10,(10,2))
p=np.random.randint(-10,10,(10,2))


[[-19  -2]
 [ 15  11]
 [ 13   9]
 [  1 -15]
 [ 10 -12]
 [ 17 -17]
 [-13   0]
 [ 16  -8]
 [  7 -19]
 [ 19 -18]]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    print(U)
    U = U.reshape(len(U),1)
    print(U)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[  2.01697466  -0.29872304   0.71567971  -0.02031127   2.68724093
   0.87675492  -0.73739554 -17.79178031   0.44610523   1.25398665]
[[  2.01697466]
 [ -0.29872304]
 [  0.71567971]
 [ -0.02031127]
 [  2.68724093]
 [  0.87675492]
 [ -0.73739554]
 [-17.79178031]
 [  0.44610523]
 [  1.25398665]]
[ 9.9338462  15.4250107  13.83689198 12.83308487 14.48073649  8.36176514
  8.2389251   1.97115613  8.4241962   7.68740664]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
from numpy.lib import stride_tricks
b=(Z.size-3,4)
c=(Z.itemsize,Z.itemsize)
d=stride_tricks.as_strided(Z,b,c)
print(d)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
a=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(a) 
b=np.sum(S > 1e-10)
print(b)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
a=np.random.randint(1,20,(10))
print(a)
b=np.bincount(a).argmax()
print(b)

[10 12 14 17 13 19 12 19  8 18]
12


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
a=np.random.randint(1,20,(10,10))
print(a.strides)
n=3
b=a.shape[0]-n+1
c=a.shape[1]-n+1
print(b)
print(c)
d=stride_tricks.as_strided(a,shape=(b,c,n,n),strides=(a.strides+a.strides))
print(d)

(80, 8)
8
8
[[[[13 12 19]
   [ 8 12  7]
   [19 11 13]]

  [[12 19 13]
   [12  7 11]
   [11 13  2]]

  [[19 13  7]
   [ 7 11 16]
   [13  2 15]]

  [[13  7  5]
   [11 16 18]
   [ 2 15  3]]

  [[ 7  5 15]
   [16 18  9]
   [15  3  7]]

  [[ 5 15 17]
   [18  9  1]
   [ 3  7  1]]

  [[15 17  7]
   [ 9  1  8]
   [ 7  1 16]]

  [[17  7 13]
   [ 1  8 13]
   [ 1 16  5]]]


 [[[ 8 12  7]
   [19 11 13]
   [ 7 17  1]]

  [[12  7 11]
   [11 13  2]
   [17  1 12]]

  [[ 7 11 16]
   [13  2 15]
   [ 1 12  5]]

  [[11 16 18]
   [ 2 15  3]
   [12  5  2]]

  [[16 18  9]
   [15  3  7]
   [ 5  2 19]]

  [[18  9  1]
   [ 3  7  1]
   [ 2 19 18]]

  [[ 9  1  8]
   [ 7  1 16]
   [19 18 10]]

  [[ 1  8 13]
   [ 1 16  5]
   [18 10 13]]]


 [[[19 11 13]
   [ 7 17  1]
   [ 2 10  3]]

  [[11 13  2]
   [17  1 12]
   [10  3 14]]

  [[13  2 15]
   [ 1 12  5]
   [ 3 14  3]]

  [[ 2 15  3]
   [12  5  2]
   [14  3 17]]

  [[15  3  7]
   [ 5  2 19]
   [ 3 17  3]]

  [[ 3  7  1]
   [ 2 19 18]
   [17  3 12]]

  [[ 7  1 16]
  

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4 14  7  5  3]
 [14  1 13 10  2]
 [ 7 13  3 42  1]
 [ 5 10 42  0  5]
 [ 3  2  1  5  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
a=np.ones((10,5,5))
b=np.ones((10,5,1))
c=np.tensordot(a,b,axes=[[0,2],[0,1]])
print(c)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
a=np.random.randint(0,30,(16,16))
print(a)
c=a.shape[0]
d=4
b=np.add.reduceat(np.add.reduceat(a,np.arange(0,c,d),axis=0),np.arange(0,c,d),axis=1)
print(b)

[[23 18 28  7 29 12  6 10 22 12 25 24  1 12  9  2]
 [ 1  0  9  2 24  9  5 25  3  0  6 27 11 29 26 20]
 [19  2 22 27 16 26 26  1  1  8  4 19  1 24 17 14]
 [11 21  1 17 10 12 13 10  6 14 17  4 24 20 20  7]
 [25 18 20  3  8 16  5  8 24  6  3 13  6 21  1 25]
 [28 22 20 29 27 16  7 18  7 14 25  9  3 24 12  6]
 [14  0 27 12 14 24 24  3 14  5 27 22 13  2 22 12]
 [ 6  3 29  2 29 27 12 29 28  4  8  9  4 23 18  9]
 [15 28 16  6 26 11 22 16  2  0  5 23 12  4 22  5]
 [12 10 17 19  1 20 24 19 25 12 21  1  5 27 22  3]
 [ 1  1 17 27 20 12 12 23 18 29 18  0 14 11 15 20]
 [18 10 12  4 16 16 17 16 12  9 17 20 21 27 16  5]
 [20  3 15  2 16 21  6  4  1 11 12 13  4 24 25 28]
 [29 19 18 15 25  0  1  1 22 28 11  6 12  9 10 23]
 [ 6 23  6  9 13 10 27 23  2  9 14 21  8 16  1  4]
 [ 3 18 20 25  4  3  5 27 26 13  3  6 22  5 28 16]]
[[208 234 192 237]
 [258 267 218 201]
 [213 271 212 229]
 [231 186 198 235]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

[495 496 497 498 499]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
a=np.arange(500)
np.random.shuffle(a)

n=5
c=a[np.argsort(a)]
print(c[-n:])
a=np.random.randint(0,40,20)
print(a)
b=a[np.argsort(a)]
print(b)
print(b[len(a)-1:])


[33 10  7 30  5 36 17  5 32 14  7  1  1 25 25  0 39  5 31 21]
[ 0  1  1  5  5  5  7  7 10 14 17 21 25 25 30 31 32 33 36 39]
[39]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
a=np.arange(20)
b=15+np.arange(35)
import itertools
([x for x in itertools.product(a,b)])

[(0, 15),
 (0, 16),
 (0, 17),
 (0, 18),
 (0, 19),
 (0, 20),
 (0, 21),
 (0, 22),
 (0, 23),
 (0, 24),
 (0, 25),
 (0, 26),
 (0, 27),
 (0, 28),
 (0, 29),
 (0, 30),
 (0, 31),
 (0, 32),
 (0, 33),
 (0, 34),
 (0, 35),
 (0, 36),
 (0, 37),
 (0, 38),
 (0, 39),
 (0, 40),
 (0, 41),
 (0, 42),
 (0, 43),
 (0, 44),
 (0, 45),
 (0, 46),
 (0, 47),
 (0, 48),
 (0, 49),
 (1, 15),
 (1, 16),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 20),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 26),
 (1, 27),
 (1, 28),
 (1, 29),
 (1, 30),
 (1, 31),
 (1, 32),
 (1, 33),
 (1, 34),
 (1, 35),
 (1, 36),
 (1, 37),
 (1, 38),
 (1, 39),
 (1, 40),
 (1, 41),
 (1, 42),
 (1, 43),
 (1, 44),
 (1, 45),
 (1, 46),
 (1, 47),
 (1, 48),
 (1, 49),
 (2, 15),
 (2, 16),
 (2, 17),
 (2, 18),
 (2, 19),
 (2, 20),
 (2, 21),
 (2, 22),
 (2, 23),
 (2, 24),
 (2, 25),
 (2, 26),
 (2, 27),
 (2, 28),
 (2, 29),
 (2, 30),
 (2, 31),
 (2, 32),
 (2, 33),
 (2, 34),
 (2, 35),
 (2, 36),
 (2, 37),
 (2, 38),
 (2, 39),
 (2, 40),
 (2, 41),
 (2, 42),
 (2, 43),
 (2, 44),


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
a=np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
b=np.core.records.fromarrays(a.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(b)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
z=np.random.randint(0,10,50)
print(z)
b=np.power(z,3)
print(b)
c=z**3
print(c)
#d=np.einsum(z,3)
#print(d)

[1 7 1 0 8 9 1 9 2 1 4 5 6 3 4 6 2 1 0 8 8 2 3 0 6 9 9 0 9 9 3 6 4 5 6 9 1
 7 1 9 7 3 8 2 4 3 2 8 7 3]
[  1 343   1   0 512 729   1 729   8   1  64 125 216  27  64 216   8   1
   0 512 512   8  27   0 216 729 729   0 729 729  27 216  64 125 216 729
   1 343   1 729 343  27 512   8  64  27   8 512 343  27]
[  1 343   1   0 512 729   1 729   8   1  64 125 216  27  64 216   8   1
   0 512 512   8  27   0 216 729 729   0 729 729  27 216  64 125 216 729
   1 343   1 729 343  27 512   8  64  27   8 512 343  27]


TypeError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
a=np.random.randint(0,5,(2,2))
print(a)
b=np.random.randint(0,5,(2,2))
print(b)
c=np.newaxis
#c=np.where(b,a)
print(c)

[[1 2]
 [3 3]]
[[4 4]
 [0 0]]
None


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
a=np.random.randint(0,5,(10,3))
b=np.all(a[:,1:]==a[:,:-1],axis=1)
c=a[~b]
print(c)

[[3 3 4]
 [4 4 0]
 [4 3 3]
 [2 2 0]
 [3 1 4]
 [0 0 2]
 [2 1 1]
 [1 4 2]
 [0 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
a=10+np.arange(25)
b=np.array(a, dtype=np.uint8)
print(np.unpackbits(b[:, np.newaxis], axis=1))

[[0 0 0 0 1 0 1 0]
 [0 0 0 0 1 0 1 1]
 [0 0 0 0 1 1 0 0]
 [0 0 0 0 1 1 0 1]
 [0 0 0 0 1 1 1 0]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 1]
 [0 0 0 1 0 0 1 0]
 [0 0 0 1 0 0 1 1]
 [0 0 0 1 0 1 0 0]
 [0 0 0 1 0 1 0 1]
 [0 0 0 1 0 1 1 0]
 [0 0 0 1 0 1 1 1]
 [0 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 1]
 [0 0 0 1 1 0 1 0]
 [0 0 0 1 1 0 1 1]
 [0 0 0 1 1 1 0 0]
 [0 0 0 1 1 1 0 1]
 [0 0 0 1 1 1 1 0]
 [0 0 0 1 1 1 1 1]
 [0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 1 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
a=np.random.randint(0,2,(6,3))
b=np.ascontiguousarray(a).view(np.dtype((np.void, a.dtype.itemsize * a.shape[1])))
_, idx = np.unique(b, return_index=True)
uZ = a[idx]
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,3,10)
B = np.random.uniform(0,3,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B) 

array([[3.22714273, 4.43144414, 5.43813666, 0.2238399 , 1.43138828,
        2.83450454, 1.62516519, 0.25689375, 0.46218811, 2.97864438],
       [4.10412725, 5.63570073, 6.91596458, 0.28466898, 1.8203718 ,
        3.60478859, 2.0668081 , 0.3267053 , 0.58778894, 3.78809882],
       [2.92215158, 4.01263675, 4.92418866, 0.20268521, 1.29611048,
        2.56662088, 1.4715739 , 0.23261521, 0.41850759, 2.69713834],
       [0.59303287, 0.81434019, 0.9993341 , 0.04113373, 0.26303773,
        0.52088008, 0.29864696, 0.04720784, 0.08493357, 0.5473678 ],
       [3.1762313 , 4.36153364, 5.35234456, 0.2203086 , 1.40880668,
        2.78978737, 1.59952657, 0.25284099, 0.45489662, 2.93165326],
       [3.52830617, 4.8449954 , 5.94563448, 0.24472908, 1.5649683 ,
        3.09902619, 1.77682886, 0.28086759, 0.50532043, 3.25661745],
       [2.60924024, 3.5829535 , 4.39689414, 0.18098117, 1.15731971,
        2.29178065, 1.31399407, 0.20770619, 0.37369274, 2.40832198],
       [4.6335005 , 6.36262488, 7.8080243

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
a=np.array([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n=4
b=np.logical_and.reduce(np.mod(a, 1) == 0, axis=-1)
b&= (a.sum(axis=-1) == n)
print(a[b])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
a=np.random.randn(100)
b=1000 
c=np.random.randint(0, a.size, (b,a.size))
d=a[c].mean(axis=1)
e=np.percentile(d, [2.5, 97.5])
print(e)

[-0.03382916  0.37037753]
